### ISSUE TITLE
No error when used multi constructor workload.

### ISSUE THREAD

**Issue by the9ball** [Cysharp/DFrame#27]
I wrote constructor overload.

```cs
public enum ServerType
{
    A,
    B,
}

public class MultiConstructorWorkload : Workload
{
    private static string GetUrl(ServerType t) => "";

    public MultiConstructorWorkload(ServerType t) : this(GetUrl(t)) { }
    public MultiConstructorWorkload(string url) { }
    public override Task ExecuteAsync(WorkloadContext context) => Task.CompletedTask;
}
```

But, It not working and no error.
![image](https://user-images.githubusercontent.com/801466/160078871-8d6038f6-c016-415f-95de-01a186c2c25b.png)

**Comment by neuecc** [comment]
Thank you.
Multi constructor is should not allowed.
I'll make sure to validation at startup and throw an exception.

**Comment by neuecc** [comment]
Currently already validated on worker, see worker's log.
