### ISSUE TITLE
Locust equivalent values?

### ISSUE THREAD

**Issue by botondberes** [Cysharp/DFrame#40]
Hi there,

can you please provide an example for a 1-to-1 comparison with Locust?
Like let's say we wanted to use `Number of users (peak concurrency)` `10` and `Spawn rate (users started/second)` `10` for` Run time` `30s` in Locust. What values would this correspond to in DFrame and what would my `ConfigureWorker` look like?

We're trying to compare the two and possibly have an alternative to Locust that supports C#.

Thanks in advance!

**Comment by hadashiA** [comment]
Please see README for concurrency, etc.
https://github.com/Cysharp/DFrame?tab=readme-ov-file#mode

Locust and DFrame do not have the same functionality, so use your use case to decide.

> Number of users (concurrency) 

this is almost equivalent to "Concurrency".
Note that if there are multiple workers, the number of workers x concurrency is the total number of executions.

>  Spawn rate (users started/second) 10 for Run time 30s in Locust. 

Unfortunately, there seems to be no default setting to gradually increase concurrency.

It may be easier to run multiple executions in duration mode, changing the settings as you go.
Alternatively, when writing a scenario, you can refer to ExecutionContext.Workloadid to get the unique id of the virtual user.
It is probably possible to script the diversion using that.
