### ISSUE TITLE
Unique index per execution

### ISSUE THREAD

**Issue by the9ball** [Cysharp/DFrame#45]
I need unique index per execution.
Like "Counter" in jMeter.

## Use case

There is user data prepared in Database.
A unique index is needed for each execution to determine which user data should be used at this time.

### A

1. assign an Index to each Worker when calling CreateWorkloadAndSetup.
2. set the WorkerIndex in the WorkloadContext.
3. calculate based on WorkerIndex, Concurrency and ExecuteCount to be added in #44.

### B

1. query the Controller for the Index just before calling Workload.ExecuteAsync.

**Comment by hadashiA** [comment]
Merged #44, the benefits of B may not be fully understood by me, but if A meets the requirements it seems simpler.
Thanks.
